name: Publish Site

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@v1.16.0
        env:
          CNAME: 2231puppy.tech
          GO_VERSION: 1.18.4
          HUGO_VERSION: 0.101.0
          TARGET_BRANCH: gh-pages
          TARGET_REPO: https://github.com/2231puppy/2231puppy.tech
          TOKEN: ${{ secrets.PAGES_PAT }}
